# =============================================================================
# DWD-Warnungen versenden - Home Assistant Automation
# -----------------------------------------------------------------------------
# Version: 1.02
# Datum:   08.04.2023
# Quelle:  https://github.com/migacode/home-assistant/tree/main/dwd
# =============================================================================
- id: "dwd_warnings"
  alias: DWD-Warnungen versenden
  description: ""
  variables:
    alert_message: "
{# ------------------------------------------------------------------- #}
{# Entitäten der DWD-Sensoren (vollständige Namen)                     #}
{# ------------------------------------------------------------------- #}
{% set dwd_entity_name_cw = 'sensor.dwd_warnungen_hoerstel_current_warning_level' %}
{% set dwd_entity_name_aw = 'sensor.dwd_warnungen_hoerstel_advance_warning_level' %}
{# ------------------------------------------------------------------- #}
{% set number_current_warnings = state_attr(dwd_entity_name_cw, 'warning_count') %}{% set number_advanced_warnings = state_attr(dwd_entity_name_aw, 'warning_count') %}{% if ((number_current_warnings != 0 and number_current_warnings != None) or (number_advanced_warnings != 0 and number_advanced_warnings != None)) %}*DWD-WARNUNG!* (über HA){{'\n'}}{{'\n'}}{% if number_current_warnings != 0 and number_current_warnings != None %}{% for i in range(number_current_warnings) %}{{ state_attr(dwd_entity_name_cw, 'warning_' ~ loop.index ~ '_headline') | trim }}{{'\n'}}{{ 'Aktuelle Warnstufe: ' ~ state_attr(dwd_entity_name_cw, 'warning_' ~ loop.index ~ '_level') | trim }}{{'\n'}}{{ state_attr(dwd_entity_name_cw, 'warning_' ~ loop.index ~ '_description') | trim }}{{'\n'}}Von {{ state_attr(dwd_entity_name_cw, 'warning_' ~ loop.index ~ '_start') | as_timestamp | timestamp_custom('%d.%m.%Y um %H:%M Uhr', true) | trim }} bis {{ state_attr(dwd_entity_name_cw, 'warning_' ~ loop.index ~ '_end') | as_timestamp | timestamp_custom('%d.%m.%Y um %H:%M Uhr', true) | trim }}.{{'\n'}}{{'\n'}}{% endfor %}{% endif %}{% if number_advanced_warnings != 0 and number_advanced_warnings != None %}{% for i in range(number_advanced_warnings) %}{{ state_attr(dwd_entity_name_aw, 'warning_' ~ loop.index ~ '_headline') | trim }}{{'\n'}}{{ 'Erweiterte Warnstufe: ' ~ state_attr(dwd_entity_name_aw, 'warning_' ~ loop.index ~ '_level') | trim }}{{'\n'}}{{ state_attr(dwd_entity_name_aw, 'warning_' ~ loop.index ~ '_description') | trim }}{{'\n'}}Von {{ state_attr(dwd_entity_name_aw, 'warning_' ~ loop.index ~ '_start') | as_timestamp | timestamp_custom('%d.%m.%Y um %H:%M Uhr', true) | trim }} bis {{ state_attr(dwd_entity_name_aw, 'warning_' ~ loop.index ~ '_end') | as_timestamp | timestamp_custom('%d.%m.%Y um %H:%M Uhr', true) | trim }}.{{'\n'}}{{'\n'}}{% endfor %}{% endif %}{% endif %}"
  trigger:
    - platform: state
      entity_id:
        - sensor.dwd_warnungen_hoerstel_current_warning_level
      attribute: warning_count
    - platform: state
      entity_id:
        - sensor.dwd_warnungen_hoerstel_advance_warning_level
      attribute: warning_count
  action:
    - parallel:
      - service: notify.telegram_michael
        continue_on_error: true
        data:
          message: "{{ alert_message }}"
      - service: notify.mobile_app_galaxy_von_michael
        continue_on_error: true
        data:
          message: "{{ alert_message }}"
      - service: notify.persistent_notification
        continue_on_error: true
        data:
          message: "{{ alert_message }}"
      # - service: script.notify_all_michael
      #   continue_on_error: true
      #   data:
      #     message: "{{ alert_message }}"
      # - service: script.notify_all_steffi
      #   continue_on_error: true
      #   data:
      #     message: "{{ alert_message }}"
  mode: restart
